---
title: "MyHW"
author: "JIAYI HONG"
date: "9/16/2021"
output: github_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
```

```{r}
download.file("https://www.fhwa.dot.gov/bridge/nbi/2020/delimited/WI20.txt", "bridge_WI.txt")
df = read.table("bridge_WI.txt", header = T, sep = ",")
head(df)
```

https://www.fhwa.dot.gov/bridge/nbi/format.cfm 

this is the description of this df

```{r}
str(df)
```

```{r}
df_small = df %>%
  select(c("STRUCTURE_NUMBER_008", "YEAR_BUILT_027", "BRIDGE_CONDITION", # fips code ????
           "SERVICE_LEVEL_005C", "DIRECTION_005E", "COUNTY_CODE_003","DETOUR_KILOS_019", "TOLL_020", "TRAFFIC_LANES_ON_028A", 
           "TRAFFIC_LANES_UND_028B", "ADT_029", "DESIGN_LOAD_031", "DEGREES_SKEW_034", "HISTORY_037","STRUCTURE_LEN_MT_049",
           "TOTAL_IMP_COST_096", "YEAR_RECONSTRUCTED_106"))
```



```{r}
df_small_1 = df_small %>%
  filter(!is.na(BRIDGE_CONDITION) & !is.na(YEAR_BUILT_027)) %>%
  group_by(YEAR_BUILT_027, BRIDGE_CONDITION) %>%
  summarise(count = n())

df_small_1$BRIDGE_CONDITION = sub("F", "Fair", df_small_1$BRIDGE_CONDITION)
df_small_1$BRIDGE_CONDITION = sub("P", "Poor", df_small_1$BRIDGE_CONDITION)
df_small_1$BRIDGE_CONDITION = sub("G", "Good", df_small_1$BRIDGE_CONDITION)

df_small_1 %>%
  ggplot(aes(x = YEAR_BUILT_027, y = count, col = BRIDGE_CONDITION))+
  geom_point()+
  facet_wrap( ~ BRIDGE_CONDITION, scales = "free_y")+
  labs(x = "Year Built", y = "Count")+
  theme(legend.position = "none")
```

```{r}
write.csv(df, "bridge_WI.csv")

```

